### ISSUE TITLE
HTTPS requests

### ISSUE THREAD

**Issue by CollinHerber** [clugg/sm-httpreq#3]
Changing over to SSL by simply updating the URL to include https did not work.

Looking through you includes, and quite possibly do a pull request with the required code to do an SSL secure HTTP request.

If you can add this, would be great. Otherwise I'm sure I'll figure it out eventually.

If I'm missing something and this is supported, please let me know.

**Comment by clugg** [comment]
Hey Collin,
I've essentially abandoned this project (and should update the README to reflect that), but if you check out issue #1 I provided sample code for HTTP requests with SteamWorks, which as far as I'm aware does support SSL out of the box. I did write a methodmap that made SteamWorks syntax nearly exactly match this include's, so if you're interested in that let me know -- I'll likely publish it eventually anyway.
Thanks for your support anyway! :)

**Comment by CollinHerber** [comment]
Hey there. I saw that actually after submitting the issue, however would prefer to use this rather than SteamWorks. Its very lightweight and does exactly what I need it to do.

If youre able to allow SSL that would be awesome, if not no big deal.
